CREATE TABLE board(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description TEXT,
    owner_id BIGINT NOT NULL,
    created_by VARCHAR(255),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP,

    CONSTRAINT fk_board_owner
        FOREIGN KEY (owner_id) REFERENCES user_account(id) ON DELETE CASCADE
);

CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'TODO',
    position INT NOT NULL DEFAULT 0,
    board_id BIGINT NOT NULL,
    assignee_id BIGINT,
    due_date DATE,
    created_by VARCHAR(255),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP,

    CONSTRAINT fk_task_board
        FOREIGN KEY (board_id) REFERENCES board(id) ON DELETE CASCADE,

    CONSTRAINT fk_task_assignee
        FOREIGN KEY (assignee_id) REFERENCES user_account(id) ON DELETE SET NULL
);