CREATE TABLE task_comment(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    comment TEXT NOT NULL,
    created_by VARCHAR(255),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_date TIMESTAMP,

    CONSTRAINT fk_comment_task
        FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE CASCADE,

    CONSTRAINT fk_comment_author
        FOREIGN KEY (author_id) REFERENCES user_account(id) ON DELETE CASCADE
);